name: wook_application
description: wook is a simple application for Mr. Tytenko course made by Olena Patsevko

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.8
  dashed_circle: ^0.0.1
  http: ^0.12.0+2
  provider: ^4.3.2
  font_awesome_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf

